### ISSUE TITLE
It fails if pyOpenSSL is not installed

### ISSUE THREAD

**Issue by rcarrillo** [etobella/python-xmlsig#12]
It fails in a installation without `pyOpenSSL` installed, even when there is no need to use it as I'm parsing the certificates with `cryptography`.

  ```
  File "/usr/local/lib/python3.7/dist-packages/xmlsig/__init__.py", line 5, in <module>
    from .signature_context import SignatureContext
  File "/usr/local/lib/python3.7/dist-packages/xmlsig/signature_context.py", line 8, in <module>
    import OpenSSL
ModuleNotFoundError: No module named 'OpenSSL'
```

Either `pyOpenSSL` should be put as a requirement in the `setup.py` or the ability to use certificates parsed with `pyOpenSSL` should be available only if that library itself is available.

Please, tell me which way should I go, so I can provide a pull request.

Thanks!

**Comment by etobella** [comment]
Good catch! I will try to make a pr next week
