### ISSUE TITLE
Typo in test_rsa.py (`def tes_sign_case1(self)`) actually skips test.

### ISSUE THREAD

**Issue by mahmoudimus** [etobella/python-xmlsig#15]
I believe [this test](https://github.com/etobella/python-xmlsig/blob/master/tests/test_rsa.py#L103-L121) is not executed because the `unittest` runner is looking for methods named `test_xxx` and this typo causes this test to not execute.

That being said, the test actually fails. I think we need to borrow [`XML-Security/signxml`'s hack here](https://github.com/XML-Security/signxml/blob/9226dd4845fe7025ba954f92565d6caa5af117d9/signxml/__init__.py#L219-L223) in [`signature_context.py`](https://github.com/etobella/python-xmlsig/blob/master/src/xmlsig/signature_context.py#L222-L227):

```diff
     def canonicalization(self, method, node):
         """
         Canonicalizes a node following the method
         :param method: Method identification
         :type method: str
         :param node: object to canonicalize
         :type node: str
         :return: Canonicalized node in a String
         """
         if method not in constants.TransformUsageC14NMethod:
             raise Exception("Method not allowed: " + method)
         c14n_method = constants.TransformUsageC14NMethod[method]
-        return etree.tostring(
+        c14n_node = etree.tostring(
            node,
            method=c14n_method["method"],
            with_comments=c14n_method["comments"],
            exclusive=c14n_method["exclusive"],
        )
+       if c14n_method["exclusive"] is False:
+            # TODO: there must be a nicer way to do this. See also:
+            # http://www.w3.org/TR/xml-c14n, "namespace axis"
+            # http://www.w3.org/TR/xml-c14n2/#sec-Namespace-Processing
+            c14n_node = c14n_node.replace(b' xmlns=""', b'')
+        return c14n_node
```

However, even then, this test does not pass.

**Comment by mahmoudimus** [comment]
Hi @etobella - sorry for the delay here, wanted to report my findings. I figured out the issue re: [the failing test](https://github.com/etobella/python-xmlsig/blob/master/tests/test_rsa.py#L103-L121).

When [removing the signature node in this method](https://github.com/etobella/python-xmlsig/blob/eed891371a80b6f65d0a8bec252b6b6c9af9bd1d/src/xmlsig/signature_context.py#L192-L200), the generated result from [`etree.tostring(...)`](https://github.com/etobella/python-xmlsig/blob/eed891371a80b6f65d0a8bec252b6b6c9af9bd1d/src/xmlsig/signature_context.py#L222-L227) is missing a newline between the `</Data>` closing tag and the `</Envelope>` tag which generates the wrong digest value.

I think this is a result of `lxml`'s lack of proper `Text` nodes. If you were to debug this test case, you'll find that the `etree.tostring()` method generates: `b'<Envelope xmlns="urn:envelope">\n  <Data>\n\tHello, World!\n  </Data>\n  </Envelope>'` which when the digest is applied generates this digest value: `b'ZLwUdyUkLUovpCNNO8VloO1jtxY='` which is incorrect.

The actual `etree.tostring()` method *should* generate this text: `b'<Envelope xmlns="urn:envelope">\n  <Data>\n\tHello, World!\n  </Data>\n  \n</Envelope>'` which will generate the correct digest value of: `9H/rQr2Axe9hYTV2n/tCp+3UIQQ=`.

Again, for ease of use here's the diff:

```diff
-b'<Envelope xmlns="urn:envelope">\n  <Data>\n\tHello, World!\n  </Data>\n  </Envelope>'
+b'<Envelope xmlns="urn:envelope">\n  <Data>\n\tHello, World!\n  </Data>\n  \n</Envelope>'
```

Hope this helps.

**Comment by etobella** [comment]
Thanks for your comments, I will try to check it again :wink:
