### ISSUE TITLE
Update python and lxml version

### ISSUE THREAD

**Issue by carlosrve** [etobella/python-xmlsig#3]
I just test it with python 3.7 and lxml 4.3.3 and it seems to work fine.

Is there any known problem with python 3.7?
https://github.com/etobella/python-xmlsig/blob/42126654cf994bdae3d6b4ad3652ec0035fb5a26/setup.py#L47

Or with lxml for versions >3.8.0?
https://github.com/etobella/python-xmlsig/blob/42126654cf994bdae3d6b4ad3652ec0035fb5a26/setup.py#L6

I can help fix them if so.

**Comment by etobella** [comment]
There should be no problems, but I never tested it.  I will try to test more options in order to ensure which versions are allowed.  😉

**Comment by etobella** [comment]
See #4
